# Governance Effectiveness and Control of Corruption in Global Society: A Data-Driven Analysis (2013–2023)”

## Project Introduction & Objectives:

## Dataset Overview

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df1= pd.read_csv("WGI_Data_2013_2023.csv")

In [3]:
df1.head()

,Country Name,Country Code,Series Name,Series Code,2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Afghanistan,AFG,Control of Corruption: Estimate,CC.EST,-1.44596064090729,-1.36493408679962,-1.35471308231354,-1.54022777080536,-1.53007459640503,-1.50287592411041,-1.41931009292603,-1.49336087703705,-1.15226578712463,-1.18368434906006,-1.15493178367615
1,Afghanistan,AFG,Control of Corruption: Number of Sources,CC.NO.SRC,11,11,11,10,10,10,10,9,8,8,8
2,Afghanistan,AFG,Control of Corruption: Percentile Rank,CC.PER.RNK,0.947867274284363,5.28846168518066,5.7142858505249,3.80952382087708,3.80952382087708,4.7619047164917,5.7142858505249,4.7619047164917,12.380952835083,12.2641506195068,13.6792449951172
3,Afghanistan,AFG,"Control of Corruption: Percentile Rank, Lower ...",CC.PER.RNK.LOWER,0,0,0.476190477609634,0,0,0,1.42857146263123,0,4.7619047164917,4.71698093414307,6.13207530975342
4,Afghanistan,AFG,"Control of Corruption: Percentile Rank, Upper ...",CC.PER.RNK.UPPER,9.95260620117188,12.5,12.8571424484253,10,9.5238094329834,9.5238094329834,11.9047622680664,10.4761905670166,20.9523811340332,20.2830181121826,20.7547168731689

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7709 entries, 0 to 7708
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   7706 non-null   object
 1   Country Code   7704 non-null   object
 2   Series Name    7704 non-null   object
 3   Series Code    7704 non-null   object
 4   2013 [YR2013]  7704 non-null   object
 5   2014 [YR2014]  7704 non-null   object
 6   2015 [YR2015]  7704 non-null   object
 7   2016 [YR2016]  7704 non-null   object
 8   2017 [YR2017]  7704 non-null   object
 9   2018 [YR2018]  7704 non-null   object
 10  2019 [YR2019]  7704 non-null   object
 11  2020 [YR2020]  7704 non-null   object
 12  2021 [YR2021]  7704 non-null   object
 13  2022 [YR2022]  7704 non-null   object
 14  2023 [YR2023]  7704 non-null   object
dtypes: object(15)
memory usage: 903.5+ KB

In [5]:
df1.shape

(7709, 15)

In [6]:
df1.describe()

,Country Name,Country Code,Series Name,Series Code,2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
count,7706,7704,7704,7704,7704,7704,7704,7704,7704,7704,7704,7704,7704,7704,7704
unique,216,214,36,36,2279,2410,2221,2212,2231,2444,2449,2394,2348,2164,2418
top,Afghanistan,AFG,Control of Corruption: Estimate,CC.EST,9,..,9,9,8,8,8,7,7,7,8
freq,36,36,214,214,141,198,159,165,167,168,170,166,178,182,161

In [7]:
df1.columns.tolist()

['Country Name',
 'Country Code',
 'Series Name',
 'Series Code',
 '2013 [YR2013]',
 '2014 [YR2014]',
 '2015 [YR2015]',
 '2016 [YR2016]',
 '2017 [YR2017]',
 '2018 [YR2018]',
 '2019 [YR2019]',
 '2020 [YR2020]',
 '2021 [YR2021]',
 '2022 [YR2022]',
 '2023 [YR2023]']

In [8]:
df2 = pd.read_csv("HDR_2013_2023.csv")

In [9]:
df2.head()

,countryIsoCode,country,indexCode,index,dimension,indicatorCode,indicator,year,value,note
0,AFG,Afghanistan,GII,Gender Inequality Index,NaN,abr,"Adolescent Birth Rate (births per 1,000 women ...",2013,89.337,NaN
1,AFG,Afghanistan,GII,Gender Inequality Index,NaN,abr,"Adolescent Birth Rate (births per 1,000 women ...",2014,84.069,NaN
2,AFG,Afghanistan,GII,Gender Inequality Index,NaN,abr,"Adolescent Birth Rate (births per 1,000 women ...",2015,81.043,NaN
3,AFG,Afghanistan,GII,Gender Inequality Index,NaN,abr,"Adolescent Birth Rate (births per 1,000 women ...",2016,78.130,NaN
4,AFG,Afghanistan,GII,Gender Inequality Index,NaN,abr,"Adolescent Birth Rate (births per 1,000 women ...",2017,75.300,NaN

In [10]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74410 entries, 0 to 74409
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   countryIsoCode  74410 non-null  object
 1   country         74410 non-null  object
 2   indexCode       74410 non-null  object
 3   index           74410 non-null  object
 4   dimension       1090 non-null   object
 5   indicatorCode   74410 non-null  object
 6   indicator       74410 non-null  object
 7   year            74410 non-null  int64
 8   value           74387 non-null  float64
 9   note            1199 non-null   object
dtypes: float64(1), int64(1), object(8)
memory usage: 5.7+ MB

In [11]:
df2.info

<bound method DataFrame.info of       countryIsoCode      country indexCode                    index  \
0                AFG  Afghanistan       GII  Gender Inequality Index
1                AFG  Afghanistan       GII  Gender Inequality Index
2                AFG  Afghanistan       GII  Gender Inequality Index
3                AFG  Afghanistan       GII  Gender Inequality Index
4                AFG  Afghanistan       GII  Gender Inequality Index
...              ...          ...       ...                      ...
74405      ZZK.WORLD        World       GII  Gender Inequality Index
74406      ZZK.WORLD        World       GII  Gender Inequality Index
74407      ZZK.WORLD        World       GII  Gender Inequality Index
74408      ZZK.WORLD        World       GII  Gender Inequality Index
74409      ZZK.WORLD        World       GII  Gender Inequality Index

      dimension indicatorCode  \
0           NaN           abr
1           NaN           abr
2           NaN           abr
3           NaN           abr
4           NaN           abr
...         ...           ...
74405       NaN          se_m
74406       NaN          se_m
74407       NaN          se_m
74408       NaN          se_m
74409       NaN          se_m

                                               indicator  year      value note
0      Adolescent Birth Rate (births per 1,000 women ...  2013  89.337000  NaN
1      Adolescent Birth Rate (births per 1,000 women ...  2014  84.069000  NaN
2      Adolescent Birth Rate (births per 1,000 women ...  2015  81.043000  NaN
3      Adolescent Birth Rate (births per 1,000 women ...  2016  78.130000  NaN
4      Adolescent Birth Rate (births per 1,000 women ...  2017  75.300000  NaN
...                                                  ...   ...        ...  ...
74405  Population with at least some secondary educat...  2019  69.032357  NaN
74406  Population with at least some secondary educat...  2020  69.685992  NaN
74407  Population with at least some secondary educat...  2021  70.164801  NaN
74408  Population with at least some secondary educat...  2022  69.682146  NaN
74409  Population with at least some secondary educat...  2023  70.196964  NaN

[74410 rows x 10 columns]>

In [12]:
df2.describe

<bound method NDFrame.describe of       countryIsoCode      country indexCode                    index  \
0                AFG  Afghanistan       GII  Gender Inequality Index
1                AFG  Afghanistan       GII  Gender Inequality Index
2                AFG  Afghanistan       GII  Gender Inequality Index
3                AFG  Afghanistan       GII  Gender Inequality Index
4                AFG  Afghanistan       GII  Gender Inequality Index
...              ...          ...       ...                      ...
74405      ZZK.WORLD        World       GII  Gender Inequality Index
74406      ZZK.WORLD        World       GII  Gender Inequality Index
74407      ZZK.WORLD        World       GII  Gender Inequality Index
74408      ZZK.WORLD        World       GII  Gender Inequality Index
74409      ZZK.WORLD        World       GII  Gender Inequality Index

      dimension indicatorCode  \
0           NaN           abr
1           NaN           abr
2           NaN           abr
3           NaN           abr
4           NaN           abr
...         ...           ...
74405       NaN          se_m
74406       NaN          se_m
74407       NaN          se_m
74408       NaN          se_m
74409       NaN          se_m

                                               indicator  year      value note
0      Adolescent Birth Rate (births per 1,000 women ...  2013  89.337000  NaN
1      Adolescent Birth Rate (births per 1,000 women ...  2014  84.069000  NaN
2      Adolescent Birth Rate (births per 1,000 women ...  2015  81.043000  NaN
3      Adolescent Birth Rate (births per 1,000 women ...  2016  78.130000  NaN
4      Adolescent Birth Rate (births per 1,000 women ...  2017  75.300000  NaN
...                                                  ...   ...        ...  ...
74405  Population with at least some secondary educat...  2019  69.032357  NaN
74406  Population with at least some secondary educat...  2020  69.685992  NaN
74407  Population with at least some secondary educat...  2021  70.164801  NaN
74408  Population with at least some secondary educat...  2022  69.682146  NaN
74409  Population with at least some secondary educat...  2023  70.196964  NaN

[74410 rows x 10 columns]>

In [13]:
df2.columns

Index(['countryIsoCode', 'country', 'indexCode', 'index', 'dimension',
       'indicatorCode', 'indicator', 'year', 'value', 'note'],
      dtype='object')

## Data Cleaning & Transformation (Melting / Pivoting)

In [14]:
print(df1.columns.tolist())

['Country Name', 'Country Code', 'Series Name', 'Series Code', '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]', '2016 [YR2016]', '2017 [YR2017]', '2018 [YR2018]', '2019 [YR2019]', '2020 [YR2020]', '2021 [YR2021]', '2022 [YR2022]', '2023 [YR2023]']

In [21]:
df1.columns = df1.columns.str.replace(r"\s*\[YR\d+\]", "", regex=True)

selected_series = [
    "Control of Corruption: Estimate",
    "Government Effectiveness: Estimate",
    "Regulatory Quality: Estimate",
    "Rule of Law: Estimate"]

df1_filtered = df1[df1["Series Name"].isin(selected_series)]

df1_melt = df1_filtered.melt(
    id_vars=["Country Name", "Series Name"],
    var_name="Year",
    value_name="Value")


df1_melt["Year"] = pd.to_numeric(df1_melt["Year"], errors="coerce")
df1_melt["Value"] = pd.to_numeric(df1_melt["Value"], errors="coerce")


df1_clean = df1_melt.pivot_table(
    index=["Country Name", "Year"],
    columns="Series Name",
    values="Value"
).reset_index()

print("WGI clean:", df1_clean.shape)
df1_clean.head(10)

WGI clean: (2326, 6)

Series Name,Country Name,Year,Control of Corruption: Estimate,Government Effectiveness: Estimate,Regulatory Quality: Estimate,Rule of Law: Estimate
0,Afghanistan,2013.0,-1.445961,-1.401463,-1.193090,-1.609755
1,Afghanistan,2014.0,-1.364934,-1.361646,-1.124134,-1.437702
2,Afghanistan,2015.0,-1.354713,-1.397395,-1.018826,-1.516201
3,Afghanistan,2016.0,-1.540228,-1.291468,-1.339695,-1.522534
4,Afghanistan,2017.0,-1.530075,-1.386597,-1.363010,-1.581176
5,Afghanistan,2018.0,-1.502876,-1.501758,-1.138204,-1.689124
6,Afghanistan,2019.0,-1.419310,-1.519113,-1.113778,-1.742100
7,Afghanistan,2020.0,-1.493361,-1.611539,-1.389163,-1.831407
8,Afghanistan,2021.0,-1.152266,-1.670588,-1.311682,-1.877234
9,Afghanistan,2022.0,-1.183684,-1.880035,-1.271806,-1.659846

In [18]:
print("Unique quantity:", df2["indicator"].nunique())
print(df2["indicator"].unique()[:50])

Unique quantity: 51
['Adolescent Birth Rate (births per 1,000 women ages 15-19)' 'Assets (%)'
 'Child mortality (%)'
 'Carbon dioxide emissions per capita (production) (tonnes)'
 'Coefficient of human inequality' 'Cooking fuel (%)'
 'Difference from HDI value (%)' 'Drinking water (%)' 'Electricity (%)'
 'Expected Years of Schooling (years)'
 'Expected Years of Schooling, female (years)'
 'Expected Years of Schooling, male (years)'
 'Gender Development Index (value)' 'GDI Group'
 'Gender Inequality Index (value)' 'GII Rank'
 'Gross National Income Per Capita, female (2021 PPP$)'
 'Gross National Income Per Capita, male (2021 PPP$)'
 'Gross National Income Per Capita (2021 PPP$)'
 'Human Development Index (value)' 'HDI female' 'HDI male' 'HDI Rank'
 'Housing (%)' 'Inequality-adjusted Human Development Index (value)'
 'Inequality in eduation' 'Inequality in income'
 'Inequality in life expectancy' 'Life Expectancy at Birth (years)'
 'Life Expectancy at Birth, female (years)'
 'Life Expectancy at Birth, male (years)'
 'Labour force participation rate, female (% ages 15 and older)'
 'Labour force participation rate, male (% ages 15 and older)'
 'Overall loss (%)' 'Material footprint per capita (tonnes)'
 'Maternal Mortality Ratio (deaths per 100,000 live births)'
 'MPI Value (Range: 0 to 1)' 'Mean Years of Schooling (years)'
 'Mean Years of Schooling, female (years)'
 'Mean Years of Schooling, male (years)' 'Nutrition (%)'
 'Planetary pressures�adjusted Human Development Index (value)'
 'Population, total (millions)'
 'Share of seats in parliament, female (% held by women)'
 'Share of seats in parliament, male (% held by men)'
 'Difference from HDI rank' 'Sanitation (%)' 'School attendance (%)'
 'Population with at least some secondary education, female (% ages 25 and older)'
 'Population with at least some secondary education, male (% ages 25 and older)']

In [20]:
# PIVOT HDR 

df2_sub = df2[["country", "year", "indicator", "value"]].copy()
df2_sub["year"]  = pd.to_numeric(df2_sub["year"], errors="coerce")
df2_sub["value"] = pd.to_numeric(df2_sub["value"], errors="coerce")
df2_sub = df2_sub[df2_sub["year"].between(2013, 2023, inclusive="both")]

df2_pivot = df2_sub.pivot_table(
    index=["country", "year"],
    columns="indicator",
    values="value",
    aggfunc="mean"
).reset_index()

selected_indicators = [
    "Human Development Index (value)",
    "Gender Inequality Index (value)",
    "Expected Years of Schooling (years)",
    "Mean Years of Schooling (years)",
    "Gross National Income Per Capita (2021 PPP$)",
    "Life Expectancy at Birth (years)",
    "Population with at least some secondary education, female (% ages 25 and older)",
    "Population with at least some secondary education, male (% ages 25 and older)",
    "Labour force participation rate, female (% ages 15 and older)",
    "Labour force participation rate, male (% ages 15 and older)"
]

df2_pivot = df2_pivot[
    [c for c in df2_pivot.columns if c in ["country", "year"] + selected_indicators]
]

merged = pd.merge(
    df1_clean,
    df2_pivot,
    left_on=["Country Name", "Year"],
    right_on=["country", "year"],
    how="inner"
)


wgi_cols = [
    "Control of Corruption: Estimate",
    "Government Effectiveness: Estimate",
    "Regulatory Quality: Estimate",
    "Rule of Law: Estimate"
]

final_order = (
    ["Country Name", "Year"]
    + [col for col in wgi_cols if col in merged.columns]
    + [col for col in selected_indicators if col in merged.columns]
)

merged_final = merged.drop(columns=[c for c in ["country", "year"] if c in merged.columns])
merged_final = merged_final.loc[:, final_order].sort_values(["Country Name", "Year"]).reset_index(drop=True)
merged_final.shape
merged_final.head(10)

,Country Name,Year,Control of Corruption: Estimate,Government Effectiveness: Estimate,Regulatory Quality: Estimate,Rule of Law: Estimate,Human Development Index (value),Gender Inequality Index (value),Expected Years of Schooling (years),Mean Years of Schooling (years),Gross National Income Per Capita (2021 PPP$),Life Expectancy at Birth (years),"Population with at least some secondary education, female (% ages 25 and older)","Population with at least some secondary education, male (% ages 25 and older)","Labour force participation rate, female (% ages 15 and older)","Labour force participation rate, male (% ages 15 and older)"
0,Afghanistan,2013.0,-1.445961,-1.401463,-1.193090,-1.609755,0.492,0.708,10.134183,2.030677,3245.787894,62.188,3.156962,17.807337,20.90,77.06
1,Afghanistan,2014.0,-1.364934,-1.361646,-1.124134,-1.437702,0.497,0.687,10.464680,2.077493,3214.323950,62.260,3.441748,18.542849,25.78,77.08
2,Afghanistan,2015.0,-1.354713,-1.397395,-1.018826,-1.516201,0.496,0.683,10.482975,2.124310,3087.800291,62.270,4.575420,21.342409,24.25,75.77
3,Afghanistan,2016.0,-1.540228,-1.291468,-1.339695,-1.522534,0.495,0.682,10.501270,2.268592,2818.611013,62.646,5.229826,23.629828,22.71,74.47
4,Afghanistan,2017.0,-1.530075,-1.386597,-1.363010,-1.581176,0.496,0.679,10.519565,2.412873,2783.873555,62.406,5.884233,25.917246,21.17,73.16
5,Afghanistan,2018.0,-1.502876,-1.501758,-1.138204,-1.689124,0.498,0.677,10.537860,2.557155,2758.820419,62.443,6.369394,25.953569,19.61,71.06
6,Afghanistan,2019.0,-1.419310,-1.519113,-1.113778,-1.742100,0.507,0.676,10.621292,2.701437,2969.987690,62.941,6.854554,25.989892,18.05,68.95
7,Afghanistan,2020.0,-1.493361,-1.611539,-1.389163,-1.831407,0.501,0.674,10.705385,2.845718,2797.703558,61.454,7.339715,26.026215,16.50,66.84
8,Afghanistan,2021.0,-1.152266,-1.670588,-1.311682,-1.877234,0.486,0.642,10.790143,2.990000,2151.783518,60.417,6.400000,14.870000,23.30,76.96
9,Afghanistan,2022.0,-1.183684,-1.880035,-1.271806,-1.659846,0.495,0.665,10.790143,2.514790,1960.945925,65.617,7.042050,24.077040,23.45,88.62