# Governance Effectiveness and Control of Corruption in Global Society: A Data-Driven Analysis (2013–2023)”

In [4]:
import pandas as pd
import numpy as np

In [6]:
df= pd.read_csv("WGI_Data_2013_2023.csv")

In [7]:
df.head()

,Country Name,Country Code,Series Name,Series Code,2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Afghanistan,AFG,Control of Corruption: Estimate,CC.EST,-1.44596064090729,-1.36493408679962,-1.35471308231354,-1.54022777080536,-1.53007459640503,-1.50287592411041,-1.41931009292603,-1.49336087703705,-1.15226578712463,-1.18368434906006,-1.15493178367615
1,Afghanistan,AFG,Control of Corruption: Number of Sources,CC.NO.SRC,11,11,11,10,10,10,10,9,8,8,8
2,Afghanistan,AFG,Control of Corruption: Percentile Rank,CC.PER.RNK,0.947867274284363,5.28846168518066,5.7142858505249,3.80952382087708,3.80952382087708,4.7619047164917,5.7142858505249,4.7619047164917,12.380952835083,12.2641506195068,13.6792449951172
3,Afghanistan,AFG,"Control of Corruption: Percentile Rank, Lower ...",CC.PER.RNK.LOWER,0,0,0.476190477609634,0,0,0,1.42857146263123,0,4.7619047164917,4.71698093414307,6.13207530975342
4,Afghanistan,AFG,"Control of Corruption: Percentile Rank, Upper ...",CC.PER.RNK.UPPER,9.95260620117188,12.5,12.8571424484253,10,9.5238094329834,9.5238094329834,11.9047622680664,10.4761905670166,20.9523811340332,20.2830181121826,20.7547168731689

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7709 entries, 0 to 7708
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   7706 non-null   object
 1   Country Code   7704 non-null   object
 2   Series Name    7704 non-null   object
 3   Series Code    7704 non-null   object
 4   2013 [YR2013]  7704 non-null   object
 5   2014 [YR2014]  7704 non-null   object
 6   2015 [YR2015]  7704 non-null   object
 7   2016 [YR2016]  7704 non-null   object
 8   2017 [YR2017]  7704 non-null   object
 9   2018 [YR2018]  7704 non-null   object
 10  2019 [YR2019]  7704 non-null   object
 11  2020 [YR2020]  7704 non-null   object
 12  2021 [YR2021]  7704 non-null   object
 13  2022 [YR2022]  7704 non-null   object
 14  2023 [YR2023]  7704 non-null   object
dtypes: object(15)
memory usage: 903.5+ KB

In [9]:
df.shape

(7709, 15)

In [10]:
df.describe()

,Country Name,Country Code,Series Name,Series Code,2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
count,7706,7704,7704,7704,7704,7704,7704,7704,7704,7704,7704,7704,7704,7704,7704
unique,216,214,36,36,2279,2410,2221,2212,2231,2444,2449,2394,2348,2164,2418
top,Afghanistan,AFG,Control of Corruption: Estimate,CC.EST,9,..,9,9,8,8,8,7,7,7,8
freq,36,36,214,214,141,198,159,165,167,168,170,166,178,182,161

In [12]:
df.columns

Index(['Country Name', 'Country Code', 'Series Name', 'Series Code',
       '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]', '2016 [YR2016]',
       '2017 [YR2017]', '2018 [YR2018]', '2019 [YR2019]', '2020 [YR2020]',
       '2021 [YR2021]', '2022 [YR2022]', '2023 [YR2023]'],
      dtype='object')

In [19]:
df2 = pd.read_csv("HDR_2013_2023.csv")

In [20]:
df2.head()

,countryIsoCode,country,indexCode,index,dimension,indicatorCode,indicator,year,value,note
0,AFG,Afghanistan,GII,Gender Inequality Index,NaN,abr,"Adolescent Birth Rate (births per 1,000 women ...",2013,89.337,NaN
1,AFG,Afghanistan,GII,Gender Inequality Index,NaN,abr,"Adolescent Birth Rate (births per 1,000 women ...",2014,84.069,NaN
2,AFG,Afghanistan,GII,Gender Inequality Index,NaN,abr,"Adolescent Birth Rate (births per 1,000 women ...",2015,81.043,NaN
3,AFG,Afghanistan,GII,Gender Inequality Index,NaN,abr,"Adolescent Birth Rate (births per 1,000 women ...",2016,78.130,NaN
4,AFG,Afghanistan,GII,Gender Inequality Index,NaN,abr,"Adolescent Birth Rate (births per 1,000 women ...",2017,75.300,NaN

In [25]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74410 entries, 0 to 74409
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   countryIsoCode  74410 non-null  object
 1   country         74410 non-null  object
 2   indexCode       74410 non-null  object
 3   index           74410 non-null  object
 4   dimension       1090 non-null   object
 5   indicatorCode   74410 non-null  object
 6   indicator       74410 non-null  object
 7   year            74410 non-null  int64
 8   value           74387 non-null  float64
 9   note            1199 non-null   object
dtypes: float64(1), int64(1), object(8)
memory usage: 5.7+ MB

In [24]:
df2.info

<bound method DataFrame.info of       countryIsoCode      country indexCode                    index  \
0                AFG  Afghanistan       GII  Gender Inequality Index
1                AFG  Afghanistan       GII  Gender Inequality Index
2                AFG  Afghanistan       GII  Gender Inequality Index
3                AFG  Afghanistan       GII  Gender Inequality Index
4                AFG  Afghanistan       GII  Gender Inequality Index
...              ...          ...       ...                      ...
74405      ZZK.WORLD        World       GII  Gender Inequality Index
74406      ZZK.WORLD        World       GII  Gender Inequality Index
74407      ZZK.WORLD        World       GII  Gender Inequality Index
74408      ZZK.WORLD        World       GII  Gender Inequality Index
74409      ZZK.WORLD        World       GII  Gender Inequality Index

      dimension indicatorCode  \
0           NaN           abr
1           NaN           abr
2           NaN           abr
3           NaN           abr
4           NaN           abr
...         ...           ...
74405       NaN          se_m
74406       NaN          se_m
74407       NaN          se_m
74408       NaN          se_m
74409       NaN          se_m

                                               indicator  year      value note
0      Adolescent Birth Rate (births per 1,000 women ...  2013  89.337000  NaN
1      Adolescent Birth Rate (births per 1,000 women ...  2014  84.069000  NaN
2      Adolescent Birth Rate (births per 1,000 women ...  2015  81.043000  NaN
3      Adolescent Birth Rate (births per 1,000 women ...  2016  78.130000  NaN
4      Adolescent Birth Rate (births per 1,000 women ...  2017  75.300000  NaN
...                                                  ...   ...        ...  ...
74405  Population with at least some secondary educat...  2019  69.032357  NaN
74406  Population with at least some secondary educat...  2020  69.685992  NaN
74407  Population with at least some secondary educat...  2021  70.164801  NaN
74408  Population with at least some secondary educat...  2022  69.682146  NaN
74409  Population with at least some secondary educat...  2023  70.196964  NaN

[74410 rows x 10 columns]>

In [26]:
df2.describe

<bound method NDFrame.describe of       countryIsoCode      country indexCode                    index  \
0                AFG  Afghanistan       GII  Gender Inequality Index
1                AFG  Afghanistan       GII  Gender Inequality Index
2                AFG  Afghanistan       GII  Gender Inequality Index
3                AFG  Afghanistan       GII  Gender Inequality Index
4                AFG  Afghanistan       GII  Gender Inequality Index
...              ...          ...       ...                      ...
74405      ZZK.WORLD        World       GII  Gender Inequality Index
74406      ZZK.WORLD        World       GII  Gender Inequality Index
74407      ZZK.WORLD        World       GII  Gender Inequality Index
74408      ZZK.WORLD        World       GII  Gender Inequality Index
74409      ZZK.WORLD        World       GII  Gender Inequality Index

      dimension indicatorCode  \
0           NaN           abr
1           NaN           abr
2           NaN           abr
3           NaN           abr
4           NaN           abr
...         ...           ...
74405       NaN          se_m
74406       NaN          se_m
74407       NaN          se_m
74408       NaN          se_m
74409       NaN          se_m

                                               indicator  year      value note
0      Adolescent Birth Rate (births per 1,000 women ...  2013  89.337000  NaN
1      Adolescent Birth Rate (births per 1,000 women ...  2014  84.069000  NaN
2      Adolescent Birth Rate (births per 1,000 women ...  2015  81.043000  NaN
3      Adolescent Birth Rate (births per 1,000 women ...  2016  78.130000  NaN
4      Adolescent Birth Rate (births per 1,000 women ...  2017  75.300000  NaN
...                                                  ...   ...        ...  ...
74405  Population with at least some secondary educat...  2019  69.032357  NaN
74406  Population with at least some secondary educat...  2020  69.685992  NaN
74407  Population with at least some secondary educat...  2021  70.164801  NaN
74408  Population with at least some secondary educat...  2022  69.682146  NaN
74409  Population with at least some secondary educat...  2023  70.196964  NaN

[74410 rows x 10 columns]>